// MCM — Shared dashboard utilities
function toast(title,msg='',type='info'){const icons={success:'ti-circle-check',error:'ti-alert-circle',info:'ti-info-circle',warning:'ti-alert-triangle'},colors={success:'var(--green)',error:'var(--red)',info:'var(--accent)',warning:'var(--amber)'},wrap=document.getElementById('toast-wrap');if(!wrap)return;const el=document.createElement('div');el.className=`toast toast-${type}`;el.innerHTML=`<i class="ti ${icons[type]}" style="color:${colors[type]};font-size:20px;flex-shrink:0"></i><div class="toast-body"><div class="toast-title">${title}</div>${msg?`<div class="toast-msg">${msg}</div>`:''}</div>`;wrap.appendChild(el);setTimeout(()=>{el.style.animation='toastOut .25s ease forwards';setTimeout(()=>el.remove(),260)},3500)}
function openModal(id){const e=document.getElementById(id);if(e)e.classList.add('open')}
function closeModal(id){const e=document.getElementById(id);if(e)e.classList.remove('open')}
function setupModalBackdrops(){document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}))}
function toggleSidebar(){const e=document.getElementById('sidebar');if(e)e.classList.toggle('open')}
async function doLogout(){try{await window._logout()}catch{window.location.href='index.html'}}
function getGreeting(){const h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':'Good evening'}
function getInitials(name){return(name||'U').split(' ').map(n=>n[0]).join('').toUpperCase().slice(0,2)}
function initDashboardUser(user,options={}){const{avatarIds=['sidebarAvatar','topbarAvatar'],nameIds=['sidebarName'],emailIds=[],welcomeId=null,welcomeSuffix='',emoji='👋'}=options,initials=getInitials(user.name);avatarIds.forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=initials});nameIds.forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=user.name});emailIds.forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=user.email});if(welcomeId){const e=document.getElementById(welcomeId);if(e)e.textContent=`${getGreeting()}, ${(user.name||'').split(' ')[0]||'there'}${welcomeSuffix||emoji}`}}
function applyMCMBrand(){document.title=document.title.replace(/MySVL|SVL/gi,'MCM');const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),n=[];while(w.nextNode())n.push(w.currentNode);n.forEach(x=>{if(x.nodeValue&&/MySVL|SVL/i.test(x.nodeValue))x.nodeValue=x.nodeValue.replace(/MySVL/gi,'MCM').replace(/\bSVL\b/gi,'MCM')})}
function replaceNavLabel(id,label){const b=document.getElementById(id);if(!b)return;const n=[...b.childNodes].find(x=>x.nodeType===Node.TEXT_NODE&&x.nodeValue.trim());if(n)n.nodeValue=` ${label} `}
function simplifyStudentNavigation(){if(!/student-dashboard\.html/i.test(location.pathname))return;const m={'nav-slides':'Library','nav-subjects':'Courses','nav-quiz':'Quizzes','nav-flashcards':'Flashcards','nav-learninglab':'Learning Insights','nav-questarena':'Practice Arena','nav-ai':'AI Study Assistant','nav-tasks':'Tasks','nav-social':'Community','nav-chat':'Messages','nav-rooms':'Study Rooms','nav-leaderboard':'Leaderboard','nav-grades':'Grades','nav-attendance':'Attendance','nav-profile':'Profile','nav-notifications':'Notifications','nav-settings':'Settings'};Object.entries(m).forEach(([id,l])=>replaceNavLabel(id,l));['nav-skillradar','nav-pomodoro','nav-games','nav-studyarcade'].forEach(id=>{const e=document.getElementById(id);if(e)e.style.display='none'});document.querySelectorAll('.sidebar-nav .nav-label').forEach(e=>{if(e.textContent.trim().toLowerCase()==='fun zone')e.style.display='none'});const a=document.querySelector('.logo-text'),v=document.querySelector('.logo-ver');if(a)a.textContent='MCM';if(v)v.textContent='Student Platform'}
function simplifyTeacherNavigation(){if(!/teacher-dashboard\.html/i.test(location.pathname))return;const m={'my slides':'Slide Library','quiz builder':'Quizzes','my students':'Students','class discussion':'Discussion'};document.querySelectorAll('.nav-item').forEach(b=>{const t=(b.textContent||'').trim().toLowerCase(),k=Object.keys(m).find(k=>t.startsWith(k));if(k){const n=[...b.childNodes].find(x=>x.nodeType===Node.TEXT_NODE&&x.nodeValue.trim());if(n)n.nodeValue=` ${m[k]}`}});const a=document.querySelector('.logo-text'),v=document.querySelector('.logo-ver'),r=document.querySelector('.sidebar-user-role');if(a)a.textContent='MCM';if(v)v.textContent='Faculty Platform';if(r)r.textContent='Faculty · MCM';document.body.classList.add('teacher-mcm')}
function simplifyAdminNavigation(){if(!/admin-dashboard\.html/i.test(location.pathname))return;const m={'nav-dashboard':'Overview','nav-teachers':'Faculty','nav-slides':'Content Library','nav-billing':'Plans & Billing','nav-notifications':'Notifications'};Object.entries(m).forEach(([id,l])=>replaceNavLabel(id,l));const a=document.querySelector('.logo-text'),v=document.querySelector('.logo-ver'),r=document.querySelector('.sidebar-user-role');if(a)a.textContent='MCM';if(v)v.textContent='Admin Platform';if(r)r.textContent='University Admin · MCM';document.body.classList.add('admin-mcm')}
function simplifySuperAdminNavigation(){if(!/superadmin-dashboard\.html/i.test(location.pathname))return;const m={'nav-dashboard':'Overview','nav-universities':'Universities','nav-pending':'Pending Requests','nav-allusers':'All Users','nav-admins':'University Admins','nav-revenue':'Revenue','nav-plans':'Plans & Billing','nav-content':'Content','nav-broadcast':'Broadcast','nav-aiusage':'AI Usage','nav-auditlog':'Audit Log','nav-system':'System Health','nav-notifications':'Notifications','nav-settings':'Settings'};Object.entries(m).forEach(([id,l])=>replaceNavLabel(id,l));const a=document.querySelector('.logo-text'),v=document.querySelector('.logo-ver'),r=document.querySelector('.sidebar-user-role');if(a)a.textContent='MCM';if(v)v.textContent='Platform Control';if(r)r.textContent='Platform Owner · MCM';document.body.classList.add('superadmin-mcm');if(!document.getElementById('mcm-superadmin-style')){const s=document.createElement('style');s.id='mcm-superadmin-style';s.textContent=`body.superadmin-mcm{background:#070707}body.superadmin-mcm .logo-mark{background:linear-gradient(145deg,#c9a66b,#8b6b39)!important;box-shadow:0 8px 26px rgba(201,166,107,.16)!important}body.superadmin-mcm .nav-item.active{background:rgba(201,166,107,.10)!important;color:#d9bb8c!important;border-left:1px solid rgba(201,166,107,.42)!important}body.superadmin-mcm .s-card:hover,body.superadmin-mcm .card:hover{border-color:rgba(201,166,107,.22)!important}body.superadmin-mcm .page-loader>div:first-child{background:linear-gradient(145deg,#c9a66b,#8b6b39)!important}`;document.head.appendChild(s)}}
function setupMobileMenu(){if(innerWidth>=900)return;const l=document.querySelector('.topbar-left'),x=document.getElementById('mobileMenuBtn');if(!l||x)return;const b=document.createElement('button');b.className='topbar-btn';b.id='mobileMenuBtn';b.innerHTML='<i class="ti ti-menu-2"></i>';b.onclick=toggleSidebar;l.prepend(b)}
function tabSwitch(btn){btn.closest('.tab-bar').querySelectorAll('.tab-item').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}
function hidePageLoader(){const e=document.getElementById('pageLoader');if(e)e.classList.add('hide')}
Object.assign(window,{toast,openModal,closeModal,toggleSidebar,doLogout,getGreeting,getInitials,initDashboardUser,applyMCMBrand,simplifyStudentNavigation,simplifyTeacherNavigation,simplifyAdminNavigation,simplifySuperAdminNavigation,setupMobileMenu,tabSwitch,hidePageLoader});
document.addEventListener('DOMContentLoaded',()=>{applyMCMBrand();simplifyStudentNavigation();simplifyTeacherNavigation();simplifyAdminNavigation();simplifySuperAdminNavigation();setupModalBackdrops();setupMobileMenu()});