// MCM — Per-account visual theme system
(() => {
  const THEMES = {
    obsidian:{label:'Obsidian Gold',accent:'#c9a66b',accent2:'#e2c993',accentSoft:'rgba(201,166,107,.12)',accentGlow:'rgba(201,166,107,.24)',purple:'#8b6bff'},
    midnight:{label:'Midnight Blue',accent:'#6ea8ff',accent2:'#a8c7ff',accentSoft:'rgba(110,168,255,.12)',accentGlow:'rgba(110,168,255,.24)',purple:'#8b7cff'},
    emerald:{label:'Emerald',accent:'#5ed1a2',accent2:'#a7f0d0',accentSoft:'rgba(94,209,162,.12)',accentGlow:'rgba(94,209,162,.24)',purple:'#68a0ff'},
    royal:{label:'Royal Violet',accent:'#9b8cff',accent2:'#c6bfff',accentSoft:'rgba(155,140,255,.12)',accentGlow:'rgba(155,140,255,.24)',purple:'#b07cff'},
    rose:{label:'Rose',accent:'#e68aa9',accent2:'#f4bfd0',accentSoft:'rgba(230,138,169,.12)',accentGlow:'rgba(230,138,169,.24)',purple:'#a78bfa'}
  };
  function identity(){try{const raw=sessionStorage.getItem('mcm_user')||sessionStorage.getItem('msv_user');if(raw){const u=JSON.parse(raw);return u.uid||u.email||u.role||'account';}}catch{}return location.pathname.toLowerCase()}
  const key=()=>`mcm_theme_${identity()}`;
  function applyTheme(name){const t=THEMES[name]||THEMES.obsidian, r=document.documentElement;r.style.setProperty('--accent',t.accent);r.style.setProperty('--accent-2',t.accent2);r.style.setProperty('--accent-soft',t.accentSoft);r.style.setProperty('--accent-glow',t.accentGlow);r.style.setProperty('--purple',t.purple);r.dataset.mcmTheme=name;try{localStorage.setItem(key(),name)}catch{}document.querySelectorAll('[data-mcm-theme-option]').forEach(b=>b.classList.toggle('active',b.dataset.mcmThemeOption===name));}
  const currentTheme=()=>{try{return localStorage.getItem(key())||'obsidian'}catch{return'obsidian'}};
  function styles(){if(document.getElementById('mcm-theme-style'))return;const s=document.createElement('style');s.id='mcm-theme-style';s.textContent=`#mcm-theme-trigger{position:fixed;right:18px;bottom:18px;z-index:9998;width:44px;height:44px;border-radius:13px;border:1px solid rgba(255,255,255,.1);background:#121216;color:var(--accent);display:grid;place-items:center;cursor:pointer;box-shadow:0 14px 36px rgba(0,0,0,.28)}#mcm-theme-panel{position:fixed;right:18px;bottom:72px;z-index:9999;width:280px;background:#101014;border:1px solid rgba(255,255,255,.09);border-radius:16px;padding:14px;box-shadow:0 20px 55px rgba(0,0,0,.35);display:none}#mcm-theme-panel.open{display:block}.mcm-theme-options{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mcm-theme-option,.mcm-settings-theme-btn{border:1px solid rgba(255,255,255,.08);border-radius:10px;background:#0b0b0f;color:#ddd;cursor:pointer;font-size:10px}.mcm-theme-option{display:flex;align-items:center;gap:8px;padding:9px}.mcm-theme-option.active,.mcm-settings-theme-btn.active{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent-glow) inset}.mcm-theme-swatch{width:18px;height:18px;border-radius:50%;flex:none}.mcm-appearance-nav{width:calc(100% - 8px);margin:6px 4px;padding:10px 12px;border:1px solid rgba(255,255,255,.07);border-radius:10px;background:transparent;color:var(--text-secondary,#aaa);cursor:pointer;text-align:left;font:500 11px var(--font,Inter,sans-serif);display:flex;align-items:center;gap:9px}.mcm-appearance-nav:hover{background:var(--accent-soft);color:var(--accent)}.mcm-appearance-card{margin-top:16px;padding:18px;border:1px solid var(--border);border-radius:16px;background:var(--bg-card);color:var(--text-primary)}.mcm-appearance-card h3{margin:0 0 5px;font-size:14px}.mcm-appearance-card p{margin:0 0 14px;color:var(--text-muted);font-size:11px;line-height:1.55}.mcm-settings-theme-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.mcm-settings-theme-btn{padding:9px;text-align:left;background:transparent;color:var(--text-primary)}.mcm-settings-theme-btn .dot{display:block;width:100%;height:24px;border-radius:8px;margin-bottom:7px}.mcm-settings-theme-btn strong{font-size:10px;display:block}.mcm-settings-theme-btn small{display:block;color:var(--text-muted);font-size:8px;margin-top:2px}@media(max-width:760px){.mcm-settings-theme-grid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
  function buttons(container,settings=false){container.innerHTML=Object.entries(THEMES).map(([k,t])=>settings?`<button type="button" class="mcm-settings-theme-btn" data-mcm-theme-option="${k}"><span class="dot" style="background:linear-gradient(135deg,#090909 0 55%,${t.accent} 56%)"></span><strong>${t.label}</strong><small>Personal</small></button>`:`<button type="button" class="mcm-theme-option" data-mcm-theme-option="${k}"><span class="mcm-theme-swatch" style="background:${t.accent}"></span><span>${t.label}</span></button>`).join('');container.querySelectorAll('[data-mcm-theme-option]').forEach(b=>b.onclick=()=>applyTheme(b.dataset.mcmThemeOption));}
  function settingsSection(){return[...document.querySelectorAll('.page-section,.section')].find(e=>/settings/i.test(e.id||''))||null}
  function openAppearance(){if(location.pathname.toLowerCase().includes('appearance.html'))return;location.href='appearance.html'}
  function injectNav(){
    const nav=document.querySelector('.sidebar-nav,.sidebar nav,aside nav,.nav');if(!nav)return;
    const settingsBtn=document.getElementById('nav-settings');
    if(settingsBtn){
      settingsBtn.onclick=openAppearance;
      const textNode=[...settingsBtn.childNodes].find(n=>n.nodeType===Node.TEXT_NODE&&n.nodeValue.trim());
      if(textNode)textNode.nodeValue=' Appearance ';
      const icon=settingsBtn.querySelector('i');if(icon)icon.className='ti ti-palette';
      settingsBtn.title='Open Appearance settings';
    }
    if(document.getElementById('mcm-appearance-nav'))return;
    if(!/student-dashboard\.html|teacher-dashboard\.html|admin-dashboard\.html|superadmin-dashboard\.html|svl-dashboard\.html/i.test(location.pathname))return;
    const b=document.createElement('button');b.id='mcm-appearance-nav';b.className='mcm-appearance-nav';b.innerHTML='<i class="ti ti-palette"></i><span>Appearance</span>';b.onclick=openAppearance;nav.appendChild(b);
  }
  function injectSettings(){const s=settingsSection();if(!s||s.querySelector('.mcm-appearance-card'))return;const c=document.createElement('section');c.className='mcm-appearance-card';c.innerHTML='<h3><i class="ti ti-palette"></i> Appearance</h3><p>Choose the colour palette for this account. Your selection is saved privately and does not change other accounts.</p><div class="mcm-settings-theme-grid"></div>';s.appendChild(c);buttons(c.querySelector('.mcm-settings-theme-grid'),true);}
  function floating(){if(document.getElementById('mcm-theme-panel'))return;const t=document.createElement('button');t.id='mcm-theme-trigger';t.type='button';t.title='Appearance';t.innerHTML='<i class="ti ti-palette"></i>';const p=document.createElement('div');p.id='mcm-theme-panel';p.innerHTML='<h4>Appearance</h4><p>Personal theme for this account only.</p><div class="mcm-theme-options"></div>';buttons(p.querySelector('.mcm-theme-options'));t.onclick=()=>p.classList.toggle('open');document.body.append(t,p)}
  function init(){styles();applyTheme(currentTheme());injectNav();injectSettings();setTimeout(injectNav,300);setTimeout(injectSettings,300);setTimeout(injectNav,1000);setTimeout(injectSettings,1000);floating()}
  window.MCMTheme={THEMES,applyTheme,currentTheme,init,openAppearance};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
